### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by CanaryWharf** [CanaryWharf/summer-code-jam-2020#1]
**Early Internet**

Current ideas include

* Gaming Site 😄 
* Chatroom 🎉 
* Start page 😕 
* Military game/sim 🚀 
* Email client 👀 
* Myspace predecessor 👍 
* [BBS](https://en.wikipedia.org/wiki/Bulletin_board_system) 👎

**Comment by Mathv87** [comment]
I would remove "Old browser" as the requirements require that that application must run in one of the current standard browsers.

**Comment by Mathv87** [comment]
Gaming Site 👎
Chatroom 👍
Start page 😕
Military game/sim 👎
Email client 👀
Myspace predecessor 😕
BBS 👍

**Comment by CanaryWharf** [comment]
We doing BBS
