### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by CanaryWharf** [CanaryWharf/summer-code-jam-2020#11]
#### Models
- ChatMessage (foreign key user, time, message)

#### Endpoints
- Join chat (Send websocket to chatroom)

#### Frontend
- Chat component

We might not need models here, we could just have it so, when we receive a message, it updates for everyone. Not sure how django channels handles it.

**Comment by ZoiksScoob** [comment]
### **Wishlist**

Some features to add on the display on the chat room:

In lobby:
- Paginated list of chat rooms available, preferably searchable

In a chat room:
- User names and time stamps next to message
- History of chat room
- User list present in sidebar

Functionality available in both lobby and individual chat room
- Deleting (or archiving?) chat room (tie this to user permissions)
- (optional) download history

**Comment by ZoiksScoob** [comment]
History added, but not retrievable to user.
No User list present either.
