### ISSUE TITLE
App name ideas

### ISSUE THREAD

**Issue by CanaryWharf** [CanaryWharf/summer-code-jam-2020#14]
For inspiration
https://en.wikipedia.org/wiki/List_of_bulletin_board_systems

**Comment by CanaryWharf** [comment]
Pyllama party

**Comment by ZoiksScoob** [comment]
**No Alpacas BBS**

**Comment by tmespe** [comment]
The llama Research Facility 
Purple cyber llamas
Llamas underground lair

**Comment by CanaryWharf** [comment]
COTLaQ - Confessions of a Teenage Llamma Queen

**Comment by berrynicecode** [comment]
Drama Llama

**Comment by Mathv87** [comment]
Llama.py Bulletin Board System

**Comment by ZoiksScoob** [comment]
COTLaQ looks a quite serious acronym. How are you pronouncing it? "Cot-lack"?

**Comment by CanaryWharf** [comment]
Yea, cot-lack. Like Kotlin, but with llamas
