### ISSUE TITLE
BBS Requirements gathering

### ISSUE THREAD

**Issue by CanaryWharf** [CanaryWharf/summer-code-jam-2020#3]
Decide on what we want, and split it into Must haves, Should haves, Could Haves. And then we work on them by time.

**Comment by CanaryWharf** [comment]
I imagine the most basic setup would be a forum.
Do we want it to be purely command line only? Or do we want to kind of emulate command line where it looks like a terminal but the buttons are clickable.

**Comment by CanaryWharf** [comment]
We could also have a latest news gatherer (Could just use the hackernews api)

**Comment by CanaryWharf** [comment]
Some boards also had games, it might be too much trouble, but we could implement a very basic tic tac toe game. Nothing special, but has network capabilities to link with another user searching/play against a robot

**Comment by ZoiksScoob** [comment]
Yeah, a newsfeed, discussion threads, and direct chat would be good starting features.
Given time, add in some upload/download features.

I do ahve a command line tictactoe game I wrote a while back as part of a tutorial, I could polish it a little :D

**Comment by CanaryWharf** [comment]
Yeah, rules say all code has to be writtin within this time frame. But I imagine it wouldn't be too nmuch trouble to write it again.

**Comment by ZoiksScoob** [comment]
Fair point, I can start from scratch with it as inspiration.

If we made a BBS command line only, wouldn't that mean we don't use this framework?

**Comment by Mathv87** [comment]
- User management
- Calender
- Chat function (?)
- news feed
- Some kind of mail thing?

**Comment by CanaryWharf** [comment]
> If we made a BBS command line only, wouldn't that mean we don't use this framework?


As in, I think the frontend should be html and js anyway, but do we want to disable the ability to click things, so they would type into a html input, or do we allow them to click the links. I'm l;eaning towards letting them click things with a mouse and have the using keyboard as optional

**Comment by CanaryWharf** [comment]
> Calender

As in, let people book appointments, or just a frontend calendar with the current date? Because the latter would be rather simple to implement

**Comment by Mathv87** [comment]
> > Calender
> 
> As in, let people book appointments, or just a frontend calendar with the current date? Because the latter would be rather simple to implement

I am not sure how hard all these things would become. I was only giving ideas at this point :p

**Comment by tmespe** [comment]
> > > Calender
> > 
> > 
> > As in, let people book appointments, or just a frontend calendar with the current date? Because the latter would be rather simple to implement
> 
> I am not sure how hard all these things would become. I was only giving ideas at this point :p

We could do a list of upcoming events or something? Or let people create events/rooms people can join?

Sorry, I accidentally pressed "comment and close"

**Comment by tmespe** [comment]
I think 

- User management (**must have**)
- news feed (**must have**)
- Chat function/ Forum threads (**must have**)
- Some kind of mail/private message thing (**should have**) 
- Calender (**could have**)
- upload/download  (**could have**)
- Simple Games (**could have)**
